name: Code Analysis

on: [push, pull_request]

jobs:
  build:
    name: Code Style Check and Static Analysis
    strategy:
      matrix:
        php-versions: ['8.2']

    runs-on: ubuntu-latest

    env:
      COMPOSER_NO_INTERACTION: 1

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl, curl
          ini-values: post_max_size=256M, log_errors=1
          coverage: none # disable xdebug, pcov
          tools: composer:v2

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ matrix.php }}-${{ matrix.dependency-version }}-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php }}-${{ matrix.dependency-version }}

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run PHPCS for the codestyle
        if: ${{ always() }}
        run: composer phpcs

      - name: phpmd static code analysis
        if: ${{ always() }}
        run: ./vendor/bin/phpmd src xml phpmd-ruleset.xml --ignore-violations-on-exit

      - name: phpstan
        if: ${{ always() }}
        run: composer phpstan

      - name: Psalm
        if: ${{ always() }}
        uses: docker://vimeo/psalm-github-actions
        with:
          security_analysis: true
          report_file: results.sarif

      - name: Upload Security Analysis results to GitHub
        if: ${{ always() }}
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif